version: '3'

silent: true

tasks:
  install:
    desc: install tools required for development or build
    cmds: [ task: install-golangci-lint ]

  install-golangci-lint:
    desc: install golangci-lint
    cmds: [ third_party/golangci-lint/download.sh ]

  world:
    desc: run - literally - evertyhing ;)
    cmds:
      - task: lint
      - task: test

  test:
    cmds: [ go test ./... ]

  lint:
    desc: lint app
    cmds: [ third_party/golangci-lint/golangci-lint run ]

  default:
    cmds: [ task: world ]
