on:
  push:
  pull_request:

name: test branches or pull requests

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: "1.16"
      - uses: arduino/setup-task@v1
      - run: task install
      - run: task world
